---
- name: Create application directory
  ansible.builtin.file:
    path: /opt/flask-app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Copy Flask application
  ansible.builtin.copy:
    src: ../../../app/app.py
    dest: /opt/flask-app/app.py
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Copy Python requirements
  ansible.builtin.copy:
    src: ../../../app/requirements.txt
    dest: /opt/flask-app/requirements.txt
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Create Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /opt/flask-app/venv
    creates: /opt/flask-app/venv/bin/activate

- name: Install Flask application dependencies
  ansible.builtin.pip:
    requirements: /opt/flask-app/requirements.txt
    virtualenv: /opt/flask-app/venv
